services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: libro
      POSTGRES_PASSWORD: libro
      POSTGRES_DB: libro
    ports:
      - "5433:5432"   
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  dbdata:
